/**
 * Sample Rule Checker Output
 *
 * Generated by running:
 *   python3 src/lib/rule-checker/rule_checker.py
 *
 * This is the pre-computed output used by the frontend. When the backend
 * API is connected, it will run the Python checker live and return the
 * same structure.
 */

import type { RuleCheckerReport } from "./types";

export const SAMPLE_REPORT: RuleCheckerReport = {
  total_checks: 34,
  passed: 3,
  warnings: 24,
  errors: 7,
  results: [
    {
      check_name: "Duplicate IP Address",
      status: "ERROR",
      evidence:
        "IP 192.168.10.1 is assigned to: R1:GigabitEthernet0/0, R2:GigabitEthernet0/2",
      explanation:
        "Two or more interfaces share the same IP address (192.168.10.1). This causes ARP conflicts and unpredictable routing behavior.",
      recommended_action:
        "Assign a unique IP to one of: R1:GigabitEthernet0/0, R2:GigabitEthernet0/2. Verify with 'show ip arp' and 'show ip interface brief'.",
    },
    {
      check_name: "Incorrect Subnet Mask",
      status: "ERROR",
      evidence: "SW1:FastEthernet0/2 has /32 mask (255.255.255.255)",
      explanation:
        "A /32 mask (255.255.255.255) designates a host route, not a network segment. This is almost certainly a configuration error on an interface meant for LAN or WAN use.",
      recommended_action:
        "Set the correct prefix for the network. Common values: /24 (255.255.255.0) for LANs, /30 (255.255.255.252) for point-to-point links.",
    },
    {
      check_name: "Incorrect Subnet Mask",
      status: "WARNING",
      evidence: "SW1:FastEthernet0/2 uses /32 on a non-loopback interface",
      explanation:
        "Point-to-point links typically use /30 or /31. A /32 mask on a physical interface may prevent communication with the peer.",
      recommended_action:
        "Use /30 (255.255.255.252) for point-to-point links, or /24 (255.255.255.0) for LAN segments.",
    },
    {
      check_name: "Default Gateway Mismatch",
      status: "WARNING",
      evidence: "Device 'R1' has no default gateway configured.",
      explanation:
        "A device with multiple routed interfaces but no default gateway cannot reach networks outside its directly connected subnets.",
      recommended_action:
        "Set a default gateway: 'ip default-gateway <ip>' for L2 switches, or a default route 'ip route 0.0.0.0 0.0.0.0 <next-hop>' for routers.",
    },
    {
      check_name: "Default Gateway Mismatch",
      status: "WARNING",
      evidence: "Device 'R2' has no default gateway configured.",
      explanation:
        "A device with multiple routed interfaces but no default gateway cannot reach networks outside its directly connected subnets.",
      recommended_action:
        "Set a default gateway: 'ip default-gateway <ip>' for L2 switches, or a default route 'ip route 0.0.0.0 0.0.0.0 <next-hop>' for routers.",
    },
    {
      check_name: "Default Gateway Mismatch",
      status: "PASS",
      evidence:
        "Device 'SW1' gateway 192.168.10.1 is in the same subnet as a local interface.",
      explanation: "Default gateway is correctly placed.",
      recommended_action: "No action required.",
    },
    {
      check_name: "Default Gateway Mismatch",
      status: "PASS",
      evidence:
        "Device 'SW2' gateway 192.168.20.1 is in the same subnet as a local interface.",
      explanation: "Default gateway is correctly placed.",
      recommended_action: "No action required.",
    },
    {
      check_name: "Default Gateway Mismatch",
      status: "PASS",
      evidence:
        "Device 'PC1' gateway 192.168.10.254 is in the same subnet as a local interface.",
      explanation: "Default gateway is correctly placed.",
      recommended_action: "No action required.",
    },
    {
      check_name: "Interface Administratively Down",
      status: "ERROR",
      evidence:
        "R1:GigabitEthernet0/2 is administratively down (IP: 172.16.0.1)",
      explanation:
        "The interface is in 'shutdown' state. Any device connected to this port will have no network connectivity.",
      recommended_action:
        "On R1: 'interface GigabitEthernet0/2, no shutdown'. Verify the link comes up: 'show interfaces GigabitEthernet0/2'.",
    },
    {
      check_name: "Interface Administratively Down",
      status: "ERROR",
      evidence: "SW1:FastEthernet0/1 is administratively down",
      explanation:
        "The interface is in 'shutdown' state. Any device connected to this port will have no network connectivity.",
      recommended_action:
        "On SW1: 'interface FastEthernet0/1, no shutdown'. Verify the link comes up: 'show interfaces FastEthernet0/1'.",
    },
    {
      check_name: "Missing VLAN",
      status: "ERROR",
      evidence:
        "SW1:Vlan99 is assigned to VLAN 99, but VLAN 99 is not defined on SW1.",
      explanation:
        "An interface can only operate in a VLAN that exists on the switch. VLAN 99 must be created before the port can function.",
      recommended_action:
        "On SW1: 'vlan 99', then 'name <vlan-name>'. Verify: 'show vlan brief'.",
    },
    {
      check_name: "Missing VLAN",
      status: "ERROR",
      evidence:
        "SW2:FastEthernet0/1 is assigned to VLAN 30, but VLAN 30 is not defined on SW2.",
      explanation:
        "An interface can only operate in a VLAN that exists on the switch. VLAN 30 must be created before the port can function.",
      recommended_action:
        "On SW2: 'vlan 30', then 'name <vlan-name>'. Verify: 'show vlan brief'.",
    },
    {
      check_name: "Missing VLAN",
      status: "ERROR",
      evidence:
        "SW2:FastEthernet0/2 is assigned to VLAN 40, but VLAN 40 is not defined on SW2.",
      explanation:
        "An interface can only operate in a VLAN that exists on the switch. VLAN 40 must be created before the port can function.",
      recommended_action:
        "On SW2: 'vlan 40', then 'name <vlan-name>'. Verify: 'show vlan brief'.",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW1' has no route to 10.0.0.0/30 ( subnet of R1:GigabitEthernet0/1 ) and no default route.",
      explanation:
        "'SW1' cannot reach 10.0.0.0/30 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW1': 'ip route 10.0.0.0 255.255.255.252 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW1' has no route to 172.16.0.0/16 ( subnet of R1:GigabitEthernet0/2 ) and no default route.",
      explanation:
        "'SW1' cannot reach 172.16.0.0/16 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW1': 'ip route 172.16.0.0 255.255.0.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW1' has no route to 10.0.0.0/30 ( subnet of R2:GigabitEthernet0/0 ) and no default route.",
      explanation:
        "'SW1' cannot reach 10.0.0.0/30 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW1': 'ip route 10.0.0.0 255.255.255.252 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW1' has no route to 192.168.20.0/24 ( subnet of R2:GigabitEthernet0/1 ) and no default route.",
      explanation:
        "'SW1' cannot reach 192.168.20.0/24 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW1': 'ip route 192.168.20.0 255.255.255.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW1' has no route to 192.168.20.0/24 ( subnet of SW2:Vlan20 ) and no default route.",
      explanation:
        "'SW1' cannot reach 192.168.20.0/24 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW1': 'ip route 192.168.20.0 255.255.255.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW2' has no route to 192.168.10.0/24 ( subnet of R1:GigabitEthernet0/0 ) and no default route.",
      explanation:
        "'SW2' cannot reach 192.168.10.0/24 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW2': 'ip route 192.168.10.0 255.255.255.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW2' has no route to 10.0.0.0/30 ( subnet of R1:GigabitEthernet0/1 ) and no default route.",
      explanation:
        "'SW2' cannot reach 10.0.0.0/30 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW2': 'ip route 10.0.0.0 255.255.255.252 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW2' has no route to 172.16.0.0/16 ( subnet of R1:GigabitEthernet0/2 ) and no default route.",
      explanation:
        "'SW2' cannot reach 172.16.0.0/16 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW2': 'ip route 172.16.0.0 255.255.0.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW2' has no route to 10.0.0.0/30 ( subnet of R2:GigabitEthernet0/0 ) and no default route.",
      explanation:
        "'SW2' cannot reach 10.0.0.0/30 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW2': 'ip route 10.0.0.0 255.255.255.252 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW2' has no route to 192.168.10.0/24 ( subnet of R2:GigabitEthernet0/2 ) and no default route.",
      explanation:
        "'SW2' cannot reach 192.168.10.0/24 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW2': 'ip route 192.168.10.0 255.255.255.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW2' has no route to 192.168.10.0/24 ( subnet of SW1:Vlan10 ) and no default route.",
      explanation:
        "'SW2' cannot reach 192.168.10.0/24 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW2': 'ip route 192.168.10.0 255.255.255.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW2' has no route to 192.168.99.0/24 ( subnet of SW1:Vlan99 ) and no default route.",
      explanation:
        "'SW2' cannot reach 192.168.99.0/24 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW2': 'ip route 192.168.99.0 255.255.255.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW2' has no route to 192.168.10.50/32 ( subnet of SW1:FastEthernet0/2 ) and no default route.",
      explanation:
        "'SW2' cannot reach 192.168.10.50/32 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW2': 'ip route 192.168.10.50 255.255.255.255 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'SW2' has no route to 192.168.10.0/24 ( subnet of PC1:Nic0 ) and no default route.",
      explanation:
        "'SW2' cannot reach 192.168.10.0/24 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'SW2': 'ip route 192.168.10.0 255.255.255.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'PC1' has no route to 10.0.0.0/30 ( subnet of R1:GigabitEthernet0/1 ) and no default route.",
      explanation:
        "'PC1' cannot reach 10.0.0.0/30 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'PC1': 'ip route 10.0.0.0 255.255.255.252 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'PC1' has no route to 172.16.0.0/16 ( subnet of R1:GigabitEthernet0/2 ) and no default route.",
      explanation:
        "'PC1' cannot reach 172.16.0.0/16 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'PC1': 'ip route 172.16.0.0 255.255.0.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'PC1' has no route to 10.0.0.0/30 ( subnet of R2:GigabitEthernet0/0 ) and no default route.",
      explanation:
        "'PC1' cannot reach 10.0.0.0/30 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'PC1': 'ip route 10.0.0.0 255.255.255.252 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'PC1' has no route to 192.168.20.0/24 ( subnet of R2:GigabitEthernet0/1 ) and no default route.",
      explanation:
        "'PC1' cannot reach 192.168.20.0/24 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'PC1': 'ip route 192.168.20.0 255.255.255.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'PC1' has no route to 192.168.99.0/24 ( subnet of SW1:Vlan99 ) and no default route.",
      explanation:
        "'PC1' cannot reach 192.168.99.0/24 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'PC1': 'ip route 192.168.99.0 255.255.255.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'PC1' has no route to 192.168.10.50/32 ( subnet of SW1:FastEthernet0/2 ) and no default route.",
      explanation:
        "'PC1' cannot reach 192.168.10.50/32 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'PC1': 'ip route 192.168.10.50 255.255.255.255 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
    {
      check_name: "Missing Route",
      status: "WARNING",
      evidence:
        "Device 'PC1' has no route to 192.168.20.0/24 ( subnet of SW2:Vlan20 ) and no default route.",
      explanation:
        "'PC1' cannot reach 192.168.20.0/24 because it is not directly connected and no default route exists to forward unknown destinations.",
      recommended_action:
        "Add a static route on 'PC1': 'ip route 192.168.20.0 255.255.255.0 <next-hop>'. Or enable a dynamic routing protocol (OSPF, EIGRP, RIP).",
    },
  ],
};
